
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappdeployment
  labels:
    app: myinsuranceapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myinsuranceapp
  template:
    metadata:
      labels:
        app: myinsuranceapp
    spec:
      containers:
      - name: myinsuranceapp
        image: espinoza6006/myinsuranceapp:v1
        ports:
        - name: http
          containerPort: 5000