apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceapp-az-deployment
  labels:
    app: myinsuranceapp-az
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinsuranceapp-az
  template:
    metadata:
      labels:
        app: myinsuranceapp-az
    spec:
      imagePullSecrets:
      - name: acr-secret 
      containers:
      - name: myinsuranceapp-az-az
        image: myinsuranceappwilliams.azurecr.io/espinoza6006/myinsuranceapp:v1
        ports:
        - name: http
          containerPort: 5000